classes:
  0:
    safe_driving

  1:
    texting_right

  2:
    talking_phone_right

  3:
    texting_left

  4:
    talking_phone_left

  5:
    operating_radio

  6:
    drinking

  7:
    reaching_behind

  8:
    hair_makeup

  9:
    talking_passenger
