models:
  resnet50:
    num_classes: 10
    pretrained: True
    input_size: 224
    classifier:
      dropout: 0.5
      hidden_dim: null
    fine_tuning:
      freeze_backbone: False
      unfreeze_from_layer: null
    use_batch_norm: True

  efficientnet_b3:
    num_classes: 10
    pretrained: True
    input_size: 300
    classifier:
      dropout: 0.5
      hidden_dim: null
    fine_tuning:
      freeze_backbone: False
      unfreeze_from_layer: -5
    use_batch_norm: True